services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - Ontology_group
    volumes:
      - mongodb_data:/data/db
      - ./setup:/home/mongodb/setup
    healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5


  lov_server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
            REPO_URL: "https://github.com/ProyectoPIONERA/Ontology-Hub-Scripts.git"
            BRANCH_NAME: "dev"
            REPO_NAME: "Ontology-Hub-Scripts"
            REPO_PATRONES: "https://github.com/oeg-upm/GrOwEr.git"

    env_file:
      - .env
    container_name: lov_server
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3333:3333"
    networks:
      - Ontology_group
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ontology_hub_folder:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: elasticsearch_9_2_4
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=OntologyHub2026
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false  # <--- ESTO ES VITAL
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65535
        hard: 65535
    networks:
      - Ontology_group
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ontology_hub_folder:/app

networks:
  Ontology_group:
    name: Ontology_group_network

volumes:
  ontology_hub_folder:
    name: ontology_hub_folder
  mongodb_data:
  elastic_data:
