services:
  mongodb:
    image: jarueda/oeg_lov:mongodb
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - Ontology_group
    volumes:
      - mongodb_data:/data/db
    #  - ./setup:/home/mongodb/setup
    healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5


  lov_server:
    image: jarueda/oeg_lov:lov
    env_file:
      - .env
    container_name: lov_server
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3333:3333"
    networks:
      - Ontology_group




  elasticsearch:
    image: jarueda/oeg_lov:elasticsearch
    container_name: elasticsearch_2_4_2
    ports:
      - "9200:9200"
      - "9300:9300"
    user: root
    command: > 
      elasticsearch -Des.mapper.allow_dots_in_name=true
    environment:
      ES_JAVA_OPTS: "-Dmapper.allow_dots_in_name=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65535
        hard: 65535
    networks:
      - Ontology_group


networks:
  Ontology_group:
    name: Ontology_group_network

volumes:
  ontology_hub_folder:
    name: ontology_hub_folder
  mongodb_data:
